import os
import scipy.io
import re

FLOWERS_TYPES_MAP = {
    43: "alpine sea holly",
    71: "buttercup",
    40: "fire lily",
    105: "anthurium",
    102: "californian poppy",
    162: "foxglove",
    78: "artichoke",
    91: "camellia",
    166: "frangipani",
    96: "azalea",
    82: "canna lily",
    91: "fritillary",
    46: "ball moss",
    40: "canterbury bells",
    45: "garden phlox",
    49: "balloon flower",
    108: "cape flower",
    67: "gaura",
    127: "barbeton daisy",
    52: "carnation",
    78: "gazania",
    54: "bearded iris",
    50: "cautleya spicata",
    114: "geranium",
    66: "bee balm",
    112: "clematis",
    56: "giant white arum lily",
    85: "bird of paradise",
    87: "colt's foot",
    45: "globe thistle",
    109: "bishop of llandaff",
    86: "columbine",
    41: "globe-flower",
    54: "black-eyed susan",
    92: "common dandelion",
    41: "grape hyacinth",
    48: "blackberry lily",
    41: "corn poppy",
    56: "great masterwort",
    49: "blanket flower",
    154: "cyclamen",
    60: "hard-leaved pocket orchid",
    40: "bolero deep blue",
    59: "daffodil",
    131: "hibiscus",
    128: "bougainvillea",
    63: "desert-rose",
    76: "hippeastrum",
    63: "bromelia",
    65: "english marigold",
    55: "japanese anemone",
    49: "king protea",
    82: "peruvian lily",
    66: "stemless gentian",
    67: "lenten rose",
    258: "petunia",
    61: "sunflower",
    137: "lotus",
    59: "pincushion flower",
    56: "sweet pea",
    46: "love in the mist",
    40: "pink primrose",
    85: "sweet william",
    63: "magnolia",
    109: "pink-yellow dahlia",
    130: "sword lily",
    66: "mallow",
    93: "poinsettia",
    120: "thorn apple",
    67: "marigold",
    93: "primula",
    45: "tiger lily",
    40: "mexican aster",
    40: "prince of wales feathers",
    41: "toad lily",
    82: "mexican petunia",
    85: "purple coneflower",
    58: "tree mallow",
    46: "monkshood",
    42: "red ginger",
    62: "tree poppy",
    40: "moon orchid",
    171: "rose",
    58: "trumpet creeper",
    107: "morning glory",
    75: "ruby-lipped cattleya",
    196: "wallflower",
    67: "orange dahlia",
    41: "siam tulip",
    194: "water lily",
    61: "osteospermum",
    52: "silverbush",
    184: "watercress",
    49: "oxeye daisy",
    87: "snapdragon",
    85: "wild pansy",
    251: "passion flower",
    48: "spear thistle",
    54: "windflower",
    71: "pelargonium",
    42: "spring crocus",
    49: "yellow iris",
}

FLOWERS_TYPES = (
    scipy.io.loadmat(os.getenv("FLOWERS_MAT", "flowers.mat")).get("labels").tolist()[0]
)


def map_flower_type(
    filename: str, types: list = FLOWERS_TYPES, tmap: dict = FLOWERS_TYPES_MAP
):
    # extract the original index from the file name
    i = int("".join(re.findall("\d", filename)))
    return types[i]
